### Health Checker
GET http://localhost:8080/api/health-checker
Accept: application/json

### create game
POST http://localhost:8080/api/games/game
Content-Type: application/json

{
  "field_name":"Soccer Planet",
  "address": "444 NW Miami FL 32342",
  "day": "Mon 12-00"
}

### get all games
GET http://localhost:8080/api/games
Content-Type: application/json

### get game by ID
GET http://localhost:8080/api/games/game/3a6403a9-527e-439a-a9c9-412e12d3be09
Content-Type: application/json

### update game by ID
PUT http://localhost:8080/api/games/game/3a6403a9-527e-439a-a9c9-412e12d3be09
Content-Type: application/json

{
  "field_name":"Soccer UPDATED",
  "address": "UPDATED ADDRESS"
}

### delete game by ID
DELETE http://localhost:8080/api/games/game/3a6403a9-527e-439a-a9c9-412e12d3be09